baseURL = "/"
languageCode = "en-us"
title = "Haskell Guide"
theme = "kube"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 286
[Params]
  RSSLink = "/index.xml"
  author = "geoffreyhuntley" # add your company name
  github = "haskellguides" # add your github profile name
  twitter = "geoffreyhuntley" # add your twitter profile
  email = "ghuntley@ghuntley.com"

[[menu.main]]
    name = "Learn Haskell"
    weight = -200
    url = "/learn/"
[[menu.main]]
    name = "Guidance"
    weight = -100
    url = "/guides/"
[[menu.main]]
    name = "Community"
    weight = 900
    url = "/community/"
